@Backend_HostAddress = https://localhost:5001

POST {{Backend_HostAddress}}/api/authentication/RegisterUser
Content-Type: application/json
{
    "userName": "John",
    "fullName": "John Doe",
    "email": "filip.jeftic95@gmail.com",
    "password": "sampita",
    "birthDate": "1990-05-15T00:00:00Z",
    "address": "Cara Dusana",
    "userType": "User"
}

###

POST {{Backend_HostAddress}}/api/authentication/AuthenticateUser
Content-Type: application/json
{
  "email": "filip.jeftic95@gmail.com",
  "password": "sampita"
}

###
